"""
MotionFix V12 (FRDM-inspired) — Training Script

Training strategy (aligned with FRDM):
  - foot_only=False: dual-head output (pos + delta), full body reconstruction
  - Contact-gated foot loss: high weight on contact frames, low on air frames
  - Velocity-position consistency loss: CumSum(delta) ≈ pos_shift
  - Epsilon-insensitive loss: small deviations not penalized

Uses training_data_v12 (generated by prepare_data_v12.py)
"""

import torch
import torch.optim as optim
from torch.utils.data import DataLoader
import os
import time
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from motionfix_model_v12 import MotionFixNetworkV12, MotionFixLossV12
from dataset_v12 import MotionFixDatasetV12

BATCH_SIZE = 32
NUM_EPOCHS = 50
LEARNING_RATE = 0.0001
DATA_DIR = "../training_data_v12"
SAVE_DIR = "checkpoints_v12"
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'


def train():
    print("=" * 60)
    print("MotionFix V12 (FRDM-inspired) - Training")
    print("  Dual-head output + Contact-gated loss + Vel-Pos consistency")
    print("=" * 60)
    print(f"Device: {DEVICE}")
    print(f"Data: {DATA_DIR}")
    print(f"Checkpoints: {SAVE_DIR}")

    os.makedirs(SAVE_DIR, exist_ok=True)

    # ---- Data ----
    dataset = MotionFixDatasetV12(DATA_DIR)
    loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True,
                        num_workers=2, pin_memory=True)
    print(f"Samples: {len(dataset)}, Batches/epoch: {len(loader)}")

    # ---- Model ----
    model = MotionFixNetworkV12(
        blend_alpha=0.5,
        window_size=2,
        velocity_gate=0.5,
    ).to(DEVICE)
    print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")

    # ---- Loss & Optimizer ----
    # FRDM-inspired loss weights:
    #   λ_foot_contact=5.0  — strong corrective force on contact frames
    #   λ_foot_air=0.1      — weak constraint on air frames (allow natural motion)
    #   λ_foot_vel=2.0      — foot velocity smoothness (V8 proven)
    #   λ_vel_pos=0.3       — velocity-position consistency (FRDM L_vel-pos)
    #   λ_eps=1.0           — epsilon-insensitive penalty (FRDM L_epsilon-rp)
    criterion = MotionFixLossV12(
        lambda_vel=0.5,
        lambda_foot_contact=5.0,
        lambda_foot_air=0.1,
        lambda_foot_vel=2.0,
        lambda_vel_pos=0.3,
        lambda_eps=1.0,
        epsilon=0.02,
    )
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=15, gamma=0.5)

    # ---- Resume ----
    start_epoch = 0
    resume_path = f"{SAVE_DIR}/latest.pth"
    if os.path.exists(resume_path):
        ckpt = torch.load(resume_path, map_location=DEVICE)
        model.load_state_dict(ckpt['model_state_dict'])
        optimizer.load_state_dict(ckpt['optimizer_state_dict'])
        start_epoch = ckpt['epoch'] + 1
        print(f"Resumed from epoch {start_epoch}")

    best_loss = float('inf')

    # ---- Training Loop ----
    for epoch in range(start_epoch, NUM_EPOCHS):
        model.train()
        t0 = time.time()

        total_loss = 0.0
        total_l1 = 0.0
        total_fc = 0.0
        total_fvel = 0.0
        total_vp = 0.0
        total_eps = 0.0

        for distorted, target, contact in loader:
            distorted = distorted.to(DEVICE)
            target = target.to(DEVICE)
            contact = contact.to(DEVICE)

            # Training mode: dual-head output
            pred_pos, pred_delta = model(distorted, foot_only=False)

            # FRDM-inspired loss
            loss, l_recon, l_fc, l_fvel, l_vp, l_eps = criterion(
                pred_pos, pred_delta, target, contact
            )

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            total_loss += loss.item()
            total_l1 += l_recon.item()
            total_fc += l_fc.item()
            total_fvel += l_fvel.item()
            total_vp += l_vp.item()
            total_eps += l_eps.item()

        scheduler.step()
        n = len(loader)
        elapsed = time.time() - t0
        lr = optimizer.param_groups[0]['lr']

        # Print loss breakdown
        print(
            f"Epoch {epoch+1:3d}/{NUM_EPOCHS} | "
            f"Loss: {total_loss/n:.4f} = "
            f"L1:{total_l1/n:.4f} + "
            f"FC:{total_fc/n:.4f} + "
            f"FVel:{total_fvel/n:.4f} + "
            f"VP:{total_vp/n:.4f} + "
            f"Eps:{total_eps/n:.4f} | "
            f"LR: {lr:.6f} | {elapsed:.1f}s"
        )

        # Save latest
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': total_loss / n,
        }, f"{SAVE_DIR}/latest.pth")

        # Save best
        if total_loss / n < best_loss:
            best_loss = total_loss / n
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'loss': best_loss,
            }, f"{SAVE_DIR}/best.pth")
            print(f"  -> Best model saved (loss={best_loss:.4f})")

    print(f"\nDone. Best loss: {best_loss:.4f}")
    print(f"Model: {SAVE_DIR}/best.pth")


if __name__ == "__main__":
    train()
