"""
MotionFix V13 — Training Script

V8 architecture + amplified training noise.
Trains on training_data_v13/ (generated by prepare_data_v13.py).
"""
import torch
import torch.optim as optim
from torch.utils.data import DataLoader
import os
import time
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from motionfix_model_v13 import MotionFixNetworkV13, MotionFixLossV13
from dataset_v13 import MotionFixDatasetV13

BATCH_SIZE = 32
NUM_EPOCHS = 50
LEARNING_RATE = 0.0001
DATA_DIR = "training_data_v13"
SAVE_DIR = "motionfix_v13/checkpoints_v13"
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'


def train():
    print("=" * 60)
    print("MotionFix V13 — V8 Architecture + Amplified Noise")
    print("  blend_alpha=0.5 (V8 proven)")
    print("=" * 60)
    print(f"Device: {DEVICE}")
    print(f"Data: {DATA_DIR}")
    print(f"Checkpoints: {SAVE_DIR}")

    os.makedirs(SAVE_DIR, exist_ok=True)

    # ---- Data ----
    dataset = MotionFixDatasetV13(DATA_DIR)
    loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True,
                        num_workers=2, pin_memory=True)
    print(f"Samples: {len(dataset)}, Batches/epoch: {len(loader)}")

    # ---- Model (same as V8) ----
    model = MotionFixNetworkV13(blend_alpha=0.5).to(DEVICE)
    print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")

    # ---- Loss & Optimizer (same as V8) ----
    criterion = MotionFixLossV13(lambda_vel=0.5, lambda_foot=2.0)
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=15, gamma=0.5)

    # ---- Resume ----
    start_epoch = 0
    resume_path = f"{SAVE_DIR}/latest.pth"
    if os.path.exists(resume_path):
        ckpt = torch.load(resume_path, map_location=DEVICE)
        model.load_state_dict(ckpt['model_state_dict'])
        optimizer.load_state_dict(ckpt['optimizer_state_dict'])
        start_epoch = ckpt['epoch'] + 1
        print(f"Resumed from epoch {start_epoch}")

    best_loss = float('inf')

    # ---- Training Loop ----
    for epoch in range(start_epoch, NUM_EPOCHS):
        model.train()
        t0 = time.time()
        sum_loss = sum_l1 = sum_foot = 0.0

        for distorted, target in loader:
            distorted = distorted.to(DEVICE)
            target = target.to(DEVICE)

            pred = model(distorted, foot_only=False)
            loss, l1, foot = criterion(pred, target)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            sum_loss += loss.item()
            sum_l1 += l1.item()
            sum_foot += foot.item()

        scheduler.step()
        n = len(loader)
        elapsed = time.time() - t0
        lr = optimizer.param_groups[0]['lr']

        print(f"Epoch {epoch+1:3d}/{NUM_EPOCHS} | "
              f"Loss: {sum_loss/n:.4f} (L1: {sum_l1/n:.4f}, Foot: {sum_foot/n:.4f}) | "
              f"LR: {lr:.6f} | {elapsed:.1f}s")

        # Save latest
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': sum_loss / n,
        }, f"{SAVE_DIR}/latest.pth")

        # Save best
        if sum_loss / n < best_loss:
            best_loss = sum_loss / n
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'loss': best_loss,
            }, f"{SAVE_DIR}/best.pth")
            print(f"  -> Best model saved (loss={best_loss:.4f})")

    print(f"\nDone. Best loss: {best_loss:.4f}")
    print(f"Model: {SAVE_DIR}/best.pth")


if __name__ == "__main__":
    train()
